// PCI products catalog — generated from the live pcibio.com shop + lab CSV metadata.
// 64 products; 52 include real product photography (public/products/*.jpg), listed first.
window.pciProducts = [
  {
    code: "PCI-02",
    name: "MMR QuadControl™ FFPE block",
    biomarker: "MMR",
    type: "QuadControl™",
    media: "FFPE Block",
    price: 2000,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mmr-quadcontrol-ffpe-block",
    shortDesc: "MMR IHC control — QuadControl™ FFPE Block.",
    longDesc: "The MMR QuadControl™ FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MMR immunohistochemistry, configured as a QuadControl™ panel comprising four characterized cell-line population(s). It delivers reproducible, pre-characterized MMR expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Four characterized cell-line population(s) in a QuadControl™ layout.",
    imageType: "block",
    image: "products/02_MMR_QuadControl_FFPE_block.jpg",
  },
  {
    code: "PCI-05",
    name: "MLH1/MSH6 DualControl™ Single Slide",
    biomarker: "MLH1, MSH6",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mlh1/msh6-dualcontrol-single-slide",
    shortDesc: "MLH1, MSH6 IHC control — DualControl™ Slide.",
    longDesc: "The MLH1/MSH6 DualControl™ Single Slide is a pre-sectioned cell-line control slide for MLH1, MSH6 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized MLH1, MSH6 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/05_MLH1_MSH6_DualControl_Single_Slide.jpg",
  },
  {
    code: "PCI-12",
    name: "PTEN NULL DualControl™ FFPE block",
    biomarker: "PTEN",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/ptennull-dualcontrol-ffpeblock",
    shortDesc: "PTEN IHC control — DualControl™ FFPE Block.",
    longDesc: "The PTEN NULL DualControl™ FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for PTEN immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized PTEN expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/12_PTEN_NULL_DualControl_FFPE_block.jpg",
  },
  {
    code: "PCI-13",
    name: "BRAFV600E Single control FFPE block",
    biomarker: "BRAFV600E",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/brafv600e-singlecontrol-ffpeblock",
    shortDesc: "BRAFV600E IHC control — Single Control FFPE Block.",
    longDesc: "The BRAFV600E Single control FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for BRAFV600E immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized BRAFV600E expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/13_BRAFV600E_Single_control_FFPE_block.jpg",
  },
  {
    code: "PCI-15",
    name: "p16 TriControl™ FFPE block",
    biomarker: "p16",
    type: "TriControl™",
    media: "FFPE Block",
    price: 1500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16-tricontrol-ffpe-block",
    shortDesc: "p16 IHC control — TriControl™ FFPE Block.",
    longDesc: "The p16 TriControl™ FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p16 immunohistochemistry, configured as a TriControl™ panel comprising three characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Three characterized cell-line population(s) in a TriControl™ layout.",
    imageType: "block",
    image: "products/15_p16_TriControl_FFPE_block.jpg",
  },
  {
    code: "PCI-16",
    name: "BRAFV600E DualControl™ FFPE block",
    biomarker: "BRAFV600E",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/brafv600e-dualcontrol-ffpeblock",
    shortDesc: "BRAFV600E IHC control — DualControl™ FFPE Block.",
    longDesc: "The BRAFV600E DualControl™ FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for BRAFV600E immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized BRAFV600E expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/16_BRAFV600E_DualControl_FFPE_block.jpg",
  },
  {
    code: "PCI-17",
    name: "MLH1 DualControl™ FFPE BLOCK",
    biomarker: "MLH1",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mlh1-dualcontrol-ffpe-block",
    shortDesc: "MLH1 IHC control — DualControl™ FFPE Block.",
    longDesc: "The MLH1 DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MLH1 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized MLH1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/17_MLH1_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-18",
    name: "p16 Diffuse DualControl™ FFPE BLOCK",
    biomarker: "p16",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16-diffuse-dualcontrol-ffpe-block",
    shortDesc: "p16 IHC control — DualControl™ FFPE Block.",
    longDesc: "The p16 Diffuse DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p16 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/18_p16_Diffuse_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-19",
    name: "p53 NULL DualControl™ FFPE BLOCK",
    biomarker: "p53 Null",
    type: "DualControl™",
    media: "FFPE",
    price: 900,
    cellLines: ["SKUT1", "HEK293"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-dualcontroltm-cdh5p-s7mls",
    shortDesc: "p53 Null IHC control — DualControl™ FFPE.",
    longDesc: "The p53 NULL DualControl™ FFPE BLOCK is a pre-sectioned cell-line control slide for p53 Null immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p53 Null expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/19_p53_NULL_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-20",
    name: "RB NULL DualControl™ FFPE block",
    biomarker: "RB",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/product-2-5c6mb-j8mng-zyt72-mtkdm-gds3s-7xknf",
    shortDesc: "RB IHC control — DualControl™ FFPE Block.",
    longDesc: "The RB NULL DualControl™ FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for RB immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized RB expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/20_RB_NULL_DualControl_FFPE_block.jpg",
  },
  {
    code: "PCI-21",
    name: "MSH2 DualControl™ FFPE BLOCK",
    biomarker: "MSH2",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/msh2-dualcontrol-ffpeblock",
    shortDesc: "MSH2 IHC control — DualControl™ FFPE Block.",
    longDesc: "The MSH2 DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MSH2 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized MSH2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/21_MSH2_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-22",
    name: "p53 (R248Q) DualControl™ FFPE BLOCK",
    biomarker: "p53",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-r248q-dualcontrol-ffpe-block",
    shortDesc: "p53 IHC control — DualControl™ FFPE Block.",
    longDesc: "The p53 (R248Q) DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p53 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/22_p53_R248Q_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-23",
    name: "PMS2 DualControl™ FFPE BLOCK",
    biomarker: "PMS2",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pms2-dualcontrol-ffpeblock",
    shortDesc: "PMS2 IHC control — DualControl™ FFPE Block.",
    longDesc: "The PMS2 DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for PMS2 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized PMS2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/23_PMS2_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-24",
    name: "p16 Heterogenous SINGLE CONTROL FFPE BLOCK",
    biomarker: "p16",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16mosaic-singlecontrol-ffpeblock",
    shortDesc: "p16 IHC control — Single Control FFPE Block.",
    longDesc: "The p16 Heterogenous SINGLE CONTROL FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p16 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/24_p16_Heterogenous_SINGLE_CONTROL_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-25",
    name: "PTEN-NULL Single control FFPE block",
    biomarker: "PTEN",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/ptennull-singlecontrol-ffpeblock",
    shortDesc: "PTEN IHC control — Single Control FFPE Block.",
    longDesc: "The PTEN-NULL Single control FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for PTEN immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PTEN expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/25_PTEN_NULL_Single_control_FFPE_block.jpg",
  },
  {
    code: "PCI-26",
    name: "PMS2 Deficient Single control FFPE block",
    biomarker: "PMS2",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pms2-singlecontrol-ffpeblock",
    shortDesc: "PMS2 IHC control — Single Control FFPE Block.",
    longDesc: "The PMS2 Deficient Single control FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for PMS2 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PMS2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/26_PMS2_Deficient_Single_control_FFPE_block.jpg",
  },
  {
    code: "PCI-27",
    name: "p53 (R248Q) Single control FFPE block",
    biomarker: "p53",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53r248q-singlecontrol-ffpeblock",
    shortDesc: "p53 IHC control — Single Control FFPE Block.",
    longDesc: "The p53 (R248Q) Single control FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p53 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/27_p53_R248Q_Single_control_FFPE_block.jpg",
  },
  {
    code: "PCI-28",
    name: "MSH6 Deficient Single control FFPE block",
    biomarker: "MSH6",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/msh6-singlecontrol-ffpeblock",
    shortDesc: "MSH6 IHC control — Single Control FFPE Block.",
    longDesc: "The MSH6 Deficient Single control FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MSH6 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized MSH6 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/28_MSH6_Deficient_Single_control_FFPE_block.jpg",
  },
  {
    code: "PCI-29",
    name: "MMR Intact Single Control Single Slide",
    biomarker: "MMR",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-k5bxf-cf7m5",
    shortDesc: "MMR IHC control — Single Control Slide.",
    longDesc: "The MMR Intact Single Control Single Slide is a pre-sectioned cell-line control slide for MMR immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized MMR expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/29_MMR_Intact_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-30",
    name: "p53 NULL Single Control Single Slide",
    biomarker: "p53",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-null-single-control-single-slide",
    shortDesc: "p53 IHC control — Single Control Slide.",
    longDesc: "The p53 NULL Single Control Single Slide is a pre-sectioned cell-line control slide for p53 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/30_p53_NULL_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-31",
    name: "p53 wild type Single Control Single Slide",
    biomarker: "p53",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-k5bxf-m2gh7",
    shortDesc: "p53 IHC control — Single Control Slide.",
    longDesc: "The p53 wild type Single Control Single Slide is a pre-sectioned cell-line control slide for p53 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/31_p53_wild_type_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-32",
    name: "PR negative Single Control Single Slide",
    biomarker: "PR",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-sx4xe-yl8t8",
    shortDesc: "PR IHC control — Single Control Slide.",
    longDesc: "The PR negative Single Control Single Slide is a pre-sectioned cell-line control slide for PR immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PR expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/32_PR_negative_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-33",
    name: "HER2 Negative Single Control Single Slide",
    biomarker: "HER2",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-72e8l-cdzz2",
    shortDesc: "HER2 IHC control — Single Control Slide.",
    longDesc: "The HER2 Negative Single Control Single Slide is a pre-sectioned cell-line control slide for HER2 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized HER2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/33_HER2_Negative_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-34",
    name: "HER2 AMP Single Control Single Slide",
    biomarker: "HER2",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-72e8l-xbwkn",
    shortDesc: "HER2 IHC control — Single Control Slide.",
    longDesc: "The HER2 AMP Single Control Single Slide is a pre-sectioned cell-line control slide for HER2 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized HER2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/34_HER2_AMP_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-35",
    name: "p16 OE Single Control Single Slide",
    biomarker: "p16",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-k5bxf",
    shortDesc: "p16 IHC control — Single Control Slide.",
    longDesc: "The p16 OE Single Control Single Slide is a pre-sectioned cell-line control slide for p16 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/35_p16_OE_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-36",
    name: "p16 heterogenous Single Control Single Slide",
    biomarker: "p16",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16-mosaic-single-control-single-slide",
    shortDesc: "p16 IHC control — Single Control Slide.",
    longDesc: "The p16 heterogenous Single Control Single Slide is a pre-sectioned cell-line control slide for p16 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/36_p16_heterogenous_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-37",
    name: "PTEN Wild type Single Control Single Slide",
    biomarker: "PTEN",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-sx4xe",
    shortDesc: "PTEN IHC control — Single Control Slide.",
    longDesc: "The PTEN Wild type Single Control Single Slide is a pre-sectioned cell-line control slide for PTEN immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PTEN expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/37_PTEN_Wild_type_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-38",
    name: "FOLR1 OE Single Control Single Slide",
    biomarker: "FOLR1",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-72e8l-l7c48-zgjtd",
    shortDesc: "FOLR1 IHC control — Single Control Slide.",
    longDesc: "The FOLR1 OE Single Control Single Slide is a pre-sectioned cell-line control slide for FOLR1 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized FOLR1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/38_FOLR1_OE_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-39",
    name: "FOLR1 Negative single control single slide",
    biomarker: "FOLR1",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-72e8l-l7c48-hp9tg",
    shortDesc: "FOLR1 IHC control — Single Control Slide.",
    longDesc: "The FOLR1 Negative single control single slide is a pre-sectioned cell-line control slide for FOLR1 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized FOLR1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/39_FOLR1_Negative_single_control_single_slide.jpg",
  },
  {
    code: "PCI-40",
    name: "PDL1 HIGH Single Control Single Slide",
    biomarker: "PDL-1",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-singlecontrol-slide",
    shortDesc: "PDL-1 IHC control — Single Control Slide.",
    longDesc: "The PDL1 HIGH Single Control Single Slide is a pre-sectioned cell-line control slide for PDL-1 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PDL-1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/40_PDL1_HIGH_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-41",
    name: "Wild type control SINGLE CONTROL FFPE BLOCK",
    biomarker: "—",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/wildtype-singlecontrol-ffpeblock",
    shortDesc: "— IHC control — Single Control FFPE Block.",
    longDesc: "The Wild type control SINGLE CONTROL FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for — immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized — expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/41_Wild_type_control_SINGLE_CONTROL_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-42",
    name: "p16 NULL SINGLE CONTROL FFPE BLOCK",
    biomarker: "p16 NULL",
    type: "Single Control",
    media: "FFPE",
    price: 500,
    cellLines: ["HEK-293"],
    url: "https://www.pcibio.com/shop/p/pdl1-high-single-control-ffpe-block-khjnc",
    shortDesc: "p16 NULL IHC control — Single Control FFPE.",
    longDesc: "The p16 NULL SINGLE CONTROL FFPE BLOCK is a pre-sectioned cell-line control slide for p16 NULL immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p16 NULL expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/42_p16_NULL_SINGLE_CONTROL_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-43",
    name: "MSH2 DualControl™ Single Slide",
    biomarker: "MSH2",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-3nry3-h26ay-cfhts",
    shortDesc: "MSH2 IHC control — DualControl™ Slide.",
    longDesc: "The MSH2 DualControl™ Single Slide is a pre-sectioned cell-line control slide for MSH2 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized MSH2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/43_MSH2_DualControl_Single_Slide.jpg",
  },
  {
    code: "PCI-44",
    name: "PMS2 DualControl™ Single Slide",
    biomarker: "PMS2",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pms2-dualcontrol-single-slide",
    shortDesc: "PMS2 IHC control — DualControl™ Slide.",
    longDesc: "The PMS2 DualControl™ Single Slide is a pre-sectioned cell-line control slide for PMS2 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized PMS2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/44_PMS2_DualControl_Single_Slide.jpg",
  },
  {
    code: "PCI-45",
    name: "MYC AMP Single Control Single Slide",
    biomarker: "MYC",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5-dy57n-j2wjx-m274g-4pmne-72e8l",
    shortDesc: "MYC IHC control — Single Control Slide.",
    longDesc: "The MYC AMP Single Control Single Slide is a pre-sectioned cell-line control slide for MYC immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized MYC expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/45_MYC_AMP_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-46",
    name: "PTEN deficient Single Control Single Slide",
    biomarker: "PTEN",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pten-deficient-single-control-single-slide",
    shortDesc: "PTEN IHC control — Single Control Slide.",
    longDesc: "The PTEN deficient Single Control Single Slide is a pre-sectioned cell-line control slide for PTEN immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PTEN expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/46_PTEN_deficient_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-47",
    name: "Beta-catenin Single Control Single Slide",
    biomarker: "Beta-catenin",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/beta-catenin-singlecontrol-slide",
    shortDesc: "Beta-catenin IHC control — Single Control Slide.",
    longDesc: "The Beta-catenin Single Control Single Slide is a pre-sectioned cell-line control slide for Beta-catenin immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized Beta-catenin expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/47_Beta_catenin_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-48",
    name: "BRAFV600E Single Control Single Slide",
    biomarker: "BRAFV600E",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/brafv600e-single-control-single-slide",
    shortDesc: "BRAFV600E IHC control — Single Control Slide.",
    longDesc: "The BRAFV600E Single Control Single Slide is a pre-sectioned cell-line control slide for BRAFV600E immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized BRAFV600E expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/48_BRAFV600E_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-49",
    name: "p16 Null Single Control Single Slide",
    biomarker: "p16",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16-null-single-control-single-slide",
    shortDesc: "p16 IHC control — Single Control Slide.",
    longDesc: "The p16 Null Single Control Single Slide is a pre-sectioned cell-line control slide for p16 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/49_p16_Null_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-50",
    name: "RB Null Single Control Single Slide",
    biomarker: "RB",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block-d3wfr-emlk7-z25b6-xbnt5",
    shortDesc: "RB IHC control — Single Control Slide.",
    longDesc: "The RB Null Single Control Single Slide is a pre-sectioned cell-line control slide for RB immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized RB expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/50_RB_Null_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-51",
    name: "MSH6 Single Control Single Slide",
    biomarker: "MSH6",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/msh6-single-control-single-slide",
    shortDesc: "MSH6 IHC control — Single Control Slide.",
    longDesc: "The MSH6 Single Control Single Slide is a pre-sectioned cell-line control slide for MSH6 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized MSH6 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/51_MSH6_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-52",
    name: "MLH1 Single Control Single Slide",
    biomarker: "MLH1",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mlh1-single-control-single-slide",
    shortDesc: "MLH1 IHC control — Single Control Slide.",
    longDesc: "The MLH1 Single Control Single Slide is a pre-sectioned cell-line control slide for MLH1 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized MLH1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/52_MLH1_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-53",
    name: "PMS2 Single Control Single Slide",
    biomarker: "PMS2",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pms2-singlecontrol-slide",
    shortDesc: "PMS2 IHC control — Single Control Slide.",
    longDesc: "The PMS2 Single Control Single Slide is a pre-sectioned cell-line control slide for PMS2 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PMS2 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
    image: "products/53_PMS2_Single_Control_Single_Slide.jpg",
  },
  {
    code: "PCI-54",
    name: "p53 DualControl™ Single Slide (OE and WT)",
    biomarker: "p53",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-dualcontrol-singleslide",
    shortDesc: "p53 IHC control — DualControl™ Slide.",
    longDesc: "The p53 DualControl™ Single Slide (OE and WT) is a pre-sectioned cell-line control slide for p53 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/54_p53_DualControl_Single_Slide_OE_and_WT.jpg",
  },
  {
    code: "PCI-55",
    name: "p53 TriControl™ Single Slide",
    biomarker: "p53",
    type: "TriControl™",
    media: "Slide",
    price: 45,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-tricontrol-single-slide",
    shortDesc: "p53 IHC control — TriControl™ Slide.",
    longDesc: "The p53 TriControl™ Single Slide is a pre-sectioned cell-line control slide for p53 immunohistochemistry, configured as a TriControl™ panel comprising three characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Three characterized cell-line population(s) in a TriControl™ layout.",
    imageType: "slide",
    image: "products/55_p53_TriControl_Single_Slide.jpg",
  },
  {
    code: "PCI-56",
    name: "PDL1 HIGH DualControl™ Single Slide",
    biomarker: "PDL-1",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1high-dualcontrol-singleslide",
    shortDesc: "PDL-1 IHC control — DualControl™ Slide.",
    longDesc: "The PDL1 HIGH DualControl™ Single Slide is a pre-sectioned cell-line control slide for PDL-1 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized PDL-1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/56_PDL1_HIGH_DualControl_Single_Slide.jpg",
  },
  {
    code: "PCI-57",
    name: "PDL1 HIGH DualControl™ FFPE Block",
    biomarker: "PDL-1",
    type: "DualControl™",
    media: "FFPE",
    price: 900,
    cellLines: ["RKO", "HEK293"],
    url: "https://www.pcibio.com/shop/p/pdl1-high-dualcontroltm-ffpe-block",
    shortDesc: "PDL-1 IHC control — DualControl™ FFPE.",
    longDesc: "The PDL1 HIGH DualControl™ FFPE Block is a pre-sectioned cell-line control slide for PDL-1 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized PDL-1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
    image: "products/57_PDL1_HIGH_DualControl_FFPE_Block.jpg",
  },
  {
    code: "PCI-58",
    name: "p53 TriControl™ FFPE block",
    biomarker: "p53",
    type: "TriControl™",
    media: "FFPE Block",
    price: 1500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-tricontrol-ffpe-block",
    shortDesc: "p53 IHC control — TriControl™ FFPE Block.",
    longDesc: "The p53 TriControl™ FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p53 immunohistochemistry, configured as a TriControl™ panel comprising three characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Three characterized cell-line population(s) in a TriControl™ layout.",
    imageType: "block",
    image: "products/58_p53_TriControl_FFPE_block.jpg",
  },
  {
    code: "PCI-59",
    name: "PDL1 HIGH SINGLE CONTROL FFPE BLOCK",
    biomarker: "PDL-1",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pdl1-high-single-control-ffpe-block",
    shortDesc: "PDL-1 IHC control — Single Control FFPE Block.",
    longDesc: "The PDL1 HIGH SINGLE CONTROL FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for PDL-1 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized PDL-1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/59_PDL1_HIGH_SINGLE_CONTROL_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-60",
    name: "MSH6 DualControl™ FFPE BLOCK",
    biomarker: "MSH6",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/msh6-dualcontrol-ffpe-block",
    shortDesc: "MSH6 IHC control — DualControl™ FFPE Block.",
    longDesc: "The MSH6 DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MSH6 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized MSH6 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/60_MSH6_DualControl_FFPE_BLOCK.jpg",
  },
  {
    code: "PCI-61",
    name: "p53 DualControl™ - Dualcontrol™ FFPE block (OE and WT)",
    biomarker: "p53",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/product-2-5c6mb-j8mng-zyt72-mtkdm-gds3s",
    shortDesc: "p53 IHC control — DualControl™ FFPE Block.",
    longDesc: "The p53 DualControl™ - Dualcontrol™ FFPE block (OE and WT) is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p53 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
    image: "products/61_p53_DualControl_Dualcontrol_FFPE_block_OE_and_WT.jpg",
  },
  {
    code: "PCI-62",
    name: "MLH1 Deficient Single control FFPE block",
    biomarker: "MLH1",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mlh1-singlecontrol-ffpeblock",
    shortDesc: "MLH1 IHC control — Single Control FFPE Block.",
    longDesc: "The MLH1 Deficient Single control FFPE block is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MLH1 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized MLH1 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
    image: "products/62_MLH1_Deficient_Single_control_FFPE_block.jpg",
  },
  {
    code: "PCI-00",
    name: "p16 TriControl™ Single Slide",
    biomarker: "p16",
    type: "TriControl™",
    media: "Slide",
    price: 45,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16-tricontrol-single-slide1",
    shortDesc: "p16 IHC control — TriControl™ Slide.",
    longDesc: "The p16 TriControl™ Single Slide is a pre-sectioned cell-line control slide for p16 immunohistochemistry, configured as a TriControl™ panel comprising three characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Three characterized cell-line population(s) in a TriControl™ layout.",
    imageType: "slide",
  },
  {
    code: "PCI-01",
    name: "MMR QuadControl™ Single Slide",
    biomarker: "MMR",
    type: "QuadControl™",
    media: "Slide",
    price: 60,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mmr-quadcontrol-single-slide",
    shortDesc: "MMR IHC control — QuadControl™ Slide.",
    longDesc: "The MMR QuadControl™ Single Slide is a pre-sectioned cell-line control slide for MMR immunohistochemistry, configured as a QuadControl™ panel comprising four characterized cell-line population(s). It delivers reproducible, pre-characterized MMR expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Four characterized cell-line population(s) in a QuadControl™ layout.",
    imageType: "slide",
  },
  {
    code: "PCI-03",
    name: "p53 OE Single Control Single Slide",
    biomarker: "p53",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-oe-single-control-single-slide",
    shortDesc: "p53 IHC control — Single Control Slide.",
    longDesc: "The p53 OE Single Control Single Slide is a pre-sectioned cell-line control slide for p53 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
  },
  {
    code: "PCI-04",
    name: "Beta-catenin Single Control Single Slide",
    biomarker: "Beta-catenin",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/beta-catenin-single-control-single-slide",
    shortDesc: "Beta-catenin IHC control — Single Control Slide.",
    longDesc: "The Beta-catenin Single Control Single Slide is a pre-sectioned cell-line control slide for Beta-catenin immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized Beta-catenin expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
  },
  {
    code: "PCI-06",
    name: "PTEN NULL DualControl™ Single Slide",
    biomarker: "PTEN",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/pten-null-dualcontrol-single-slide",
    shortDesc: "PTEN IHC control — DualControl™ Slide.",
    longDesc: "The PTEN NULL DualControl™ Single Slide is a pre-sectioned cell-line control slide for PTEN immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized PTEN expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "slide",
  },
  {
    code: "PCI-07",
    name: "p16 NULL/OE DualControl™ FFPE BLOCK",
    biomarker: "p16",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16-null/oe-dualcontrol-ffpe-block",
    shortDesc: "p16 IHC control — DualControl™ FFPE Block.",
    longDesc: "The p16 NULL/OE DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p16 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
  },
  {
    code: "PCI-08",
    name: "MLH1/MSH6 DualControl™ FFPE BLOCK",
    biomarker: "MLH1, MSH6",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/mlh1/msh6-dualcontrol-ffpe-block",
    shortDesc: "MLH1, MSH6 IHC control — DualControl™ FFPE Block.",
    longDesc: "The MLH1/MSH6 DualControl™ FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for MLH1, MSH6 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized MLH1, MSH6 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
  },
  {
    code: "PCI-09",
    name: "p53 P248Q Single Control Single Slide",
    biomarker: "p53",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p53-p248q-single-control-single-slide",
    shortDesc: "p53 IHC control — Single Control Slide.",
    longDesc: "The p53 P248Q Single Control Single Slide is a pre-sectioned cell-line control slide for p53 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
  },
  {
    code: "PCI-10",
    name: "Wild type Single Control Single Slide",
    biomarker: "—",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/wild-type-single-control-single-slide",
    shortDesc: "— IHC control — Single Control Slide.",
    longDesc: "The Wild type Single Control Single Slide is a pre-sectioned cell-line control slide for — immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized — expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
  },
  {
    code: "PCI-11",
    name: "p16 Diffuse SINGLE CONTROL FFPE BLOCK",
    biomarker: "p16",
    type: "Single Control",
    media: "FFPE Block",
    price: 500,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/p16diffuse-singlecontrol-ffpeblock",
    shortDesc: "p16 IHC control — Single Control FFPE Block.",
    longDesc: "The p16 Diffuse SINGLE CONTROL FFPE BLOCK is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p16 immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized p16 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "block",
  },
  {
    code: "PCI-14",
    name: "Beta-Catenin SINGLE CONTROL FFPE BLOCK",
    biomarker: "Beta-Catenin",
    type: "Single Control",
    media: "FFPE",
    price: 500,
    cellLines: ["RKO"],
    url: "https://www.pcibio.com/shop/p/pdl1-high-single-control-ffpe-block-khjnc-3hgdf-blxn2",
    shortDesc: "Beta-Catenin IHC control — Single Control FFPE.",
    longDesc: "The Beta-Catenin SINGLE CONTROL FFPE BLOCK is a pre-sectioned cell-line control slide for Beta-Catenin immunohistochemistry, configured as a Single Control panel comprising a single characterized cell-line population(s). It delivers reproducible, pre-characterized Beta-Catenin expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "A single characterized cell-line population(s) in a Single Control layout.",
    imageType: "slide",
  },
  {
    code: "PCI-63",
    name: "p53 DualControl™ - Dual control FFPE block (OE and N)",
    biomarker: "p53",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: [],
    url: "https://www.pcibio.com/shop/p/product-2-5c6mb-j8mng-zyt72-mtkdm",
    shortDesc: "p53 IHC control — DualControl™ FFPE Block.",
    longDesc: "The p53 DualControl™ - Dual control FFPE block (OE and N) is a formalin-fixed paraffin-embedded (FFPE) cell-line control block for p53 immunohistochemistry, configured as a DualControl™ panel comprising two characterized cell-line population(s). It delivers reproducible, pre-characterized p53 expression levels for calibrating, validating, and monitoring IHC staining runs.",
    composition: "Two characterized cell-line population(s) in a DualControl™ layout.",
    imageType: "block",
  },
];
