// Complete, verified PCI products catalog based on official pcibio.com shop and laboratory CSV metadata.
window.pciProducts = [
  {
    code: "PCI-FFPE-P53",
    name: "p53 TriControl™ FFPE Block",
    biomarker: "p53",
    type: "TriControl™",
    media: "FFPE Block",
    price: 1500,
    cellLines: ["SKUT1", "RKO", "HEC-1-B"],
    url: "https://www.pcibio.com/shop/p/product-1-ydar7-e8mlb-r2y28-wdkra",
    shortDesc: "Paraffin wax block.",
    longDesc: "The p53 TriControl™ FFPE block is a paraffin wax block demonstrating a p53 immunohistochemical cell line control panel specifically sequenced in a wild-type expression, overexpression, and null/negative-type pattern. The block is comprised of three cell line plugs arranged in sequence and selected for p53 IHC expression patterns.",
    composition: "3 distinct cell lines on one block.",
    cutoffs: "Calibrated against p53 hotspot sequence mutations.",
    stability: "Solid quality validation for 24+ months storage.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-P16",
    name: "p16 TriControl™ FFPE Block",
    biomarker: "P16",
    type: "TriControl™",
    media: "FFPE Block",
    price: 1500,
    cellLines: ["SKUT1", "HEK293", "RKO"],
    url: "https://www.pcibio.com/shop/p/product-1-ydar7-e8mlb-r2y28-wdkra-7xg4y",
    shortDesc: "Paraffin wax block.",
    longDesc: "The p16 TriControl™ FFPE block features three distinct cell line pellets representing negative normal, transient wildtype, and overexpressed cervical cancer control standards. Calibrated for HPV high-risk diagnostics and cervical epithelial tissue plug mimics.",
    composition: "3 unique cervical epithelial tissue plug mimics.",
    cutoffs: "HPV infection correlation controls.",
    stability: "Validated for Roche Benchmark ULTRA.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-BCAT",
    name: "Beta-catenin TriControl™ Block",
    biomarker: "Beta-Catenin",
    type: "TriControl™",
    media: "FFPE Block",
    price: 1500,
    cellLines: ["RKO", "HEC-1-A", "HEC-1-B"],
    url: "https://www.pcibio.com/shop/p/pdl1-high-single-control-ffpe-block-khjnc-3hgdf-blxn2",
    shortDesc: "Paraffin wax block.",
    longDesc: "The Beta-catenin TriControl™ block is designed to calibrate cytoplasmic, membrane-staining positive, and nuclear translocation signals. Useful for Wnt pathway verification and colon epithelial cellular micro-models.",
    composition: "3 colon epithelial cellular micro-models.",
    cutoffs: "Wnt signaling verification standards.",
    stability: "Homogeneously characterized via ELISA.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-BRAF",
    name: "BRAFV600E TriControl™ Block",
    biomarker: "BRAFV600E",
    type: "TriControl™",
    media: "FFPE Block",
    price: 1500,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/product-2-5c6mb-j8mng-zyt72-mtkdm-gds3s-7xknf-yxl7k",
    shortDesc: "Paraffin wax block.",
    longDesc: "Specially formulated block that differentiates cell line populations with and without the VE-mutant codon. Excellent for melanoma and colon tumor mutation classification and clinical IHC workflow controls.",
    composition: "Negative, weak heterozygous mutant, strong mutant plugs.",
    cutoffs: "Melanoma and colon tumor classification support.",
    stability: "Certified by digital genomic profiling.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-MSH6",
    name: "MSH6 DualControl™ FFPE Block",
    biomarker: "MSH6",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["HEC-1-B", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-DualControltm",
    shortDesc: "Paraffin wax block.",
    longDesc: "The MSH6 DualControl™ FFPE block is a mismatch repair model validation plug, showcasing wildtype intact versus homozygous gene knockout cells. Ideal for Lynch Syndrome screening and companion diagnostics.",
    composition: "Dual cell line pellet controls.",
    cutoffs: "Lynch Syndrome screening controls.",
    stability: "<5% variance in thickness layout.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-PDL1H",
    name: "PDL1 HIGH Dual FFPE Block",
    biomarker: "PDL-1",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/pdl1-high-DualControltm-ffpe-block",
    shortDesc: "Paraffin wax block.",
    longDesc: "DAB-stained threshold controls representing negative normal vs highly stained checkpoint cell-line plaques. Calibrated for Tumor Proportion Scores (TPS) at 1% and 50% benchmarks.",
    composition: "Unstained section for 22C3 or 28-8 clone optimization.",
    cutoffs: "Dynamic ranges at 1% and 50% tumor proportion scores.",
    stability: "Pathologist reviewed and certified.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-PTEN",
    name: "PTEN DualControl™ FFPE Block",
    biomarker: "PTEN",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["HEC-1-A", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3-gthws-zw3d2-f2bek",
    shortDesc: "Paraffin wax block.",
    longDesc: "The PTEN DualControl™ block displays standard cellular background staining vs complete tumor-specific PTEN loss simulation plugs. Essential for breast and prostate cancer IHC validation.",
    composition: "PTEN preservation vs complete deletion validation.",
    cutoffs: "Breast and prostate cancer IHC standards.",
    stability: "Uniform cellular arrays under controlled formalin fixation.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-HER2",
    name: "HER2 DualControl™ FFPE Block",
    biomarker: "HER2",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3-gthws-zw3d2-f2bek-yxl7k",
    shortDesc: "Paraffin wax block.",
    longDesc: "Expertly calibrated block distinguishing HER2-negative cell lines and over-amplified breast carcinoma equivalents. Aids in assessing HER2 0, 1+, and overexpressed 3+ membrane signals.",
    composition: "Distinguishes HER2 0, 1+, and overexpressed 3+ signals.",
    cutoffs: "Validated against Pathway 4B5 and HercepTest reagents.",
    stability: "Highly condensed micro-arrays.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-PR",
    name: "PR DualControl™ FFPE Block",
    biomarker: "PR",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3",
    shortDesc: "Paraffin wax block.",
    longDesc: "Double-plug breast cancer pathway verification block showing negative vs positive Progesterone nuclear stains. Ensures accuracy of clinical hormone receptor assays.",
    composition: "Fully intact cellular nuclear structure preservation.",
    cutoffs: "PgR 636 and 1E2 clones compatible.",
    stability: "Uniform cell suspension matrix.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-RB",
    name: "RB DualControl™ FFPE Block",
    biomarker: "RB",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3-gthws",
    shortDesc: "Paraffin wax block.",
    longDesc: "The Retinoblastoma (RB) DualControl™ block tests expression loss trends of nuclear RB tumor-suppressor pathways. Essential for sarcoma and pulmonary small cell tumor analysis validation.",
    composition: "Dual functional targets: retaining nuclear RB vs complete RB-mutant knockout.",
    cutoffs: "Sarcoma and pulmonary small cell tumor analysis validation.",
    stability: "Long-term solid quality validation.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-FOLR1",
    name: "FOLR1 DualControl™ FFPE Block",
    biomarker: "FOLR1",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-DualControltm-ljllf-c2af6",
    shortDesc: "Paraffin wax block.",
    longDesc: "Designed to measure expression thresholds for Folate Receptor Alpha across target epithelial linings, contrasting low baseline membranes with high endometrial tumor receptor mimics.",
    composition: "Low baseline membrane vs high endometrial tumor receptor mimics.",
    cutoffs: "Companion diagnostic assay controls.",
    stability: "Strict pathology verification.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-MYC",
    name: "MYC DualControl™ FFPE Block",
    biomarker: "MYC",
    type: "DualControl™",
    media: "FFPE Block",
    price: 900,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3",
    shortDesc: "Paraffin wax block.",
    longDesc: "Displays overexpressed oncogenic B-cell nuclear MYC signals vs standard normal lymphoid cells. Crucial for high-grade B-cell lymphoma diagnostics support.",
    composition: "Normal lymphocytes vs lymphoma model standards.",
    cutoffs: "High grade B-cell lymphoma diagnostics support.",
    stability: "Stable for multiple biopsy runs.",
    imageType: "block"
  },
  {
    code: "PCI-FFPE-MMRQ",
    name: "MMR QuadControl™ FFPE Block",
    biomarker: "MMR",
    type: "QuadControl™",
    media: "FFPE Block",
    price: 2000,
    cellLines: ["RKO", "HEK293", "HEC-1-A", "HEC-1-B"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-DualControltm-ljllf-c2af6",
    shortDesc: "Paraffin wax block.",
    longDesc: "A complete high-throughput mismatch repair model block that combines MLH1, MSH2, MSH6, and PMS2 deficient-and-proficient lines into a single validation block, optimizing laboratory workflow efficiency.",
    composition: "4 distinct human cell panels grouped together.",
    cutoffs: "Tests the entire MMR panel on a single high-throughput slide section!",
    stability: "High compatibility across major auto-stainers.",
    imageType: "block"
  },
  {
    code: "PCI-SLD-P53",
    name: "p53 TriControl™ Slide",
    biomarker: "p53",
    type: "TriControl™",
    media: "Slide",
    price: 45,
    cellLines: ["SKUT1", "RKO", "HEC-1-B"],
    url: "https://www.pcibio.com/shop/p/product-1-ydar7-e8mlb-r2y28-wdkra-64jbj",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Pre-cut paraffin sections on high-adhesive glass carrying NULL, wildtype, and overexpressed p53 control cell-line pellets. Solves slide detachment issues during high pH antigen retrieval.",
    composition: "Section Thickness: 4 microns standard.",
    cutoffs: "Poly-L-Lysine charged slides prevent detachment.",
    stability: "Individually vacuum sealed.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-P16",
    name: "p16 TriControl™ Slide",
    biomarker: "P16",
    type: "TriControl™",
    media: "Slide",
    price: 45,
    cellLines: ["SKUT1", "HEK293", "RKO"],
    url: "https://www.pcibio.com/shop/p/product-1-ydar7-e8mlb-r2y28-wdkra-7xg4y",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Ready-to-use cervical dysplasia quality control slide featuring negative, wildtype, and overexpressed p16 thresholds. Pre-cut at 4 microns for immediate diagnostic staining.",
    composition: "Matches Cintec Plus clinical assay protocols.",
    cutoffs: "Pathologist certified nuclear-cytoplasmic ratios.",
    stability: "Excellent baseline stability for runs.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-MSH6",
    name: "MSH6 DualControl™ Slide",
    biomarker: "MSH6",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: ["HEC-1-B", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-DualControltm",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Glass control slide featuring mismatch repair wildtype and complete knockout cellular segments. Placed on the bottom third of the slide to leave room for user patient samples.",
    composition: "Ready stain run controls for Lynch deficiency tests.",
    cutoffs: "Placed on bottom third, leaving rest for patient tissue sample.",
    stability: "Stable for routine IHC protocols.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-PDL1H",
    name: "PDL1 HIGH Dual Slide",
    biomarker: "PDL-1",
    type: "DualControl™",
    media: "Slide",
    price: 30,
    cellLines: ["RKO", "HEK293", "-"],
    url: "https://www.pcibio.com/shop/p/pdl1-high-DualControltm-ffpe-block-d3wfr",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Single-use control slides demonstrating tumor checkpoint expression benchmarks at 1% and 50% tumor proportion scores. Designed for NSCLC companion diagnostic validations.",
    composition: "Calibrated with clonal populations (22C3, E1L3N).",
    cutoffs: "Non-small cell lung cancer thresholds.",
    stability: "Pre-baked and vacuum packaged.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-MMRQ",
    name: "MMR QuadControl™ Slide",
    biomarker: "MMR",
    type: "QuadControl™",
    media: "Slide",
    price: 60,
    cellLines: ["RKO", "HEK293", "HEC-1-A", "HEC-1-B"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-DualControltm-ljllf-c2af6",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Four mismatch repair biomarkers (MLH1, MSH2, MSH6, PMS2) combined on a single slide. High throughput mismatch repair validation tool for rapid pathology screening.",
    composition: "Four-element cellular arrays.",
    cutoffs: "Fully standardized screen section for automated scanners.",
    stability: "Optimized for Ventana and Leica instruments.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-P53-NL",
    name: "p53 NULL Control Slide",
    biomarker: "p53",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: ["SKUT1", "-", "-"],
    url: "https://www.pcibio.com/shop/p/pms2-ffpe-block-DualControltm-cdh5p-s7mls",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Features a single cell pellet carrying deep mutated p53 hotspot sequences yielding complete staining absence. Excellent for validating negative thresholds.",
    composition: "Single p53-deficient cell-line segment.",
    cutoffs: "Confirms absence of non-specific background DAB coloration.",
    stability: "Individually vacuum wrapped.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-P53-WT",
    name: "p53 WT Control Slide",
    biomarker: "p53",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: ["RKO", "-", "-"],
    url: "https://www.pcibio.com/shop/p/product-1-ydar7-e8mlb-r2y28-wdkra",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Carries wildtype p53 standard cell lines demonstrating heterogeneous, physiological nuclear stains, avoiding clinical over-staining assay bias.",
    composition: "Single wildtype p53 cell-line pellet.",
    cutoffs: "Validates basic physiological activity.",
    stability: "Standard 4 micron sections.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-HER2-AMP",
    name: "HER2 Amplified Control Slide",
    biomarker: "HER2",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: ["HEK293", "-", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3-gthws-zw3d2-f2bek",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Presents intensely circular membrane DAB-stained cells verifying HER2 3+ expression protocols. Calibrated against breast cancer standards.",
    composition: "Single highly-amplified cell line pellet.",
    cutoffs: "Verifies gene amplification intensity match across high thresholds.",
    stability: "Pre-baked at 60C for enhanced adherence.",
    imageType: "slide"
  },
  {
    code: "PCI-SLD-HER2-NEG",
    name: "HER2 Negative Control Slide",
    biomarker: "HER2",
    type: "Single Control",
    media: "Slide",
    price: 15,
    cellLines: ["RKO", "-", "-"],
    url: "https://www.pcibio.com/shop/p/product-4-9e76d-pr6ls-5tznn-ta4x3-gthws-zw3d2-f2bek",
    shortDesc: "Adhesive glass slide section.",
    longDesc: "Presents completely stain-absent membranes verifying baseline HER2 0 boundaries to avoid false membrane score inflation.",
    composition: "Single non-amplified negative cell pellet.",
    cutoffs: "Avoids false membrane score inflation during interpretation.",
    stability: "Stable for routine IHC.",
    imageType: "slide"
  }
];
